sudo: required

dist: trusty

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

language: node_js

node_js:
  - 4.2

before_install:
  - npm install -g jspm gulp karma-cli
  - export CHROME_BIN=/usr/bin/google-chrome
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

install:
  - npm install
  - jspm install -y

script:
  - gulp lint
  - gulp test
#  - gulp build
